configure:
  scheduler:
    storage_uri: /etc/ciao/configuration.yaml
  controller:
    compute_ca: /etc/pki/ciao/controller_cert.pem
    compute_cert: /etc/pki/ciao/controller_key.pem
    identity_user: csr
    identity_password: hello
  image_service:
    url: http://glance.example.com
  launcher:
    compute_net: [198.51.100.1/24]
    mgmt_net: [198.51.100.1/24]
    disk_limit: false
    mem_limit: false
  identity_service:
    url: http://keystone.example.com
